### ISSUE TITLE
Implement 2FA

### ISSUE THREAD

**Issue by nosekefik** [3s3s/opentrade#6]
Hi!
Is planned to implement 2FA?
If not I can try to implement it.
Thanks!

**Comment by 3s3s** [comment]
Thank you. It will be great. How can i help you?

**Comment by bihonglu** [comment]
It appears that 2factor like Google Auth is not implemented,  kzv is not convinced of 2 factor so that this will not be implemented soon and this feature is not in the top list of  opentrade core devs.   
https://forum.marycoin.org/showthread.php?742-How-Can-I-enable-2-factor-at-OpenTrade-exchange

However, I still believe this is must for a serious exchange.  Most exchanges do have 2-factor choice there.  I hope someone can come and implement this feature for openTrade.  Let's leave this issue open here.
